School.Web/Models/SubjectViewModel.cs
using Microsoft.AspNetCore.Http;
using School.Web.Data.Entities;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace School.Web.Models
{
    public class SubjectViewModel : Subject
    {
        [Display(Name = "Image")]
        public IFormFile UploadFile { get; set; }

        public ICollection<IEFPSubject> IEFPSubjects { get; set; }

        public IEnumerable<Course> Courses { get; set; }

        public IEnumerable<Teacher> Teachers { get; set; }

        public IEnumerable<Student> Students { get; set; }
    }
}

School.Web/Controllers/SubjectsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using School.Web.Data.Entities;
using School.Web.Data.Repositories;
using School.Web.Helpers;
using School.Web.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;

namespace School.Web.Controllers
{
    public class SubjectsController : Controller
    {
        private readonly ISubjectRepository _subjectRepository;
        private readonly IIEFPSubjectRepository _iefpSubjectRepository;
        private readonly ICourseRepository _courseRepository;
        private readonly ITeacherRepository _teacherRepository;
        private readonly IStudentRepository _studentRepository;
        private readonly IClassRepository _classRepository;
        private readonly IGradeRepository _gradeRepository;
        private readonly IHostingEnvironment _hostingEnvironment;
        private readonly IConverterHelper _converterHelper;
        private readonly IFileHelper _fileHelper;

        public object ExcelReaderFactory { get; private set; }

        public SubjectsController(ISubjectRepository subjectRepository, IIEFPSubjectRepository iefpSubjectRepository,
            ICourseRepository courseRepository, ITeacherRepository teacherRepository, IStudentRepository studentRepository,
            IClassRepository classRepository, IGradeRepository gradeRepository, IHostingEnvironment hostingEnvironment,
            IConverterHelper converterHelper, IFileHelper fileHelper)
        {
            _subjectRepository = subjectRepository;
            _iefpSubjectRepository = iefpSubjectRepository;
            _courseRepository = courseRepository;
            _teacherRepository = teacherRepository;
            _studentRepository = studentRepository;
            _classRepository = classRepository;
            _gradeRepository = gradeRepository;
            _hostingEnvironment = hostingEnvironment;
            _converterHelper = converterHelper;
            _fileHelper = fileHelper;
        }

        // GET: SubjectsController
        public IActionResult Index()
        {
            return View(_subjectRepository.GetAll());
        }

        // GET: SubjectsController/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("SubjectNotFound");
            }

            var subject = await _subjectRepository.GetByIdAsync(id.Value);//Value pq pode vir nulo

            subject.Course = await _courseRepository.GetByIdAsync(subject.CourseId);
            subject.Teacher = await _teacherRepository.GetByIdAsync(subject.TeacherId);

            if (subject == null)
            {
                return new NotFoundViewResult("SubjectNotFound");
            }

            return View(subject);
        }

        /// <summary>
        /// Returns the Index View containing the IEFPSubjects to be converted and created as Subjects 
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Admin")]
        public IActionResult CreateIndex()
        {
            var model = new SubjectViewModel
            {
                Courses = _courseRepository.GetAll().Where(c => c.Id > 1).ToList().Where(a => a.isActive == true),
                Teachers = _teacherRepository.GetAll().Where(c => c.Id > 1).ToList().Where(a => a.isActive == true),
                IEFPSubjects = _iefpSubjectRepository.GetAll().Where(a => a.isActive == true).Where(e => e.Field == "Áudiovisuais e Produção dos Media" ||
                e.Field == "Ciências Informáticas" || e.Field == "Eletrónica e Automação").ToList()
            };

            IEnumerable<Subject> Subjects = _subjectRepository.GetAll().Where(a => a.isActive == true).ToList();

            List<IEFPSubject> ISubjects = new List<IEFPSubject>(model.IEFPSubjects);

            foreach (var iefpsubject in ISubjects)
            {
                foreach (var subject in Subjects)
                {
                    if (iefpsubject.Code == subject.Code)
                    {
                        model.IEFPSubjects.Remove(iefpsubject);
                    }
                }
            }

            return View(model);
        }

        //GET: SubjectsController/Create
        public async Task<IActionResult> Create(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("SubjectNotFound");
            }

            var iefpsubject = await _iefpSubjectRepository.GetByIdAsync(id.Value);

            var subject = _converterHelper.ConvertToSubject(iefpsubject, 1, await _courseRepository.GetByIdAsync(1),
                1, await _teacherRepository.GetByIdAsync(1), "No Selection", true);

            if (subject == null)
            {
                return new NotFoundViewResult("SubjectNotFound");
            }

            var model = _converterHelper.ToSubjectViewModel(subject, _courseRepository.GetAll().Where(c => c.Id > 1).Where(a => a.isActive == true),
                _teacherRepository.GetAll().Where(c => c.Id > 1).Where(a => a.isActive == true));

            return View(model);
        }

        // POST: ClassesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SubjectViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var iefpsubject = await _iefpSubjectRepository.GetByIdAsync(model.Id);

                    var subject = _converterHelper.ConvertToSubject(iefpsubject, model.CourseId, await _courseRepository.GetByIdAsync(model.CourseId),
                    model.TeacherId, await _teacherRepository.GetByIdAsync(model.TeacherId), model.Credits, true);

                    if (!await _subjectRepository.ExistsCodeAsync(subject.Code) && subject.isActive == true)
                        await _subjectRepository.CreateAsync(subject);

                    //GRADES

                    var Students = _studentRepository.GetAll().Where(s => s.CourseId == subject.CourseId).Where(a => a.isActive == true);

                    var Grades = new List<Grade>();

                    if (Students != null)
                    {
                        foreach (var student in Students)
                        {
                            if (student.CourseId == subject.CourseId)
                            {
                                Grades.Add(new Grade
                                {
                                    Id = 0,
                                    CourseId = student.CourseId,
                                    ClassId = student.ClassId,
                                    SubjectId = subject.Id,
                                    TeacherId = subject.TeacherId,
                                    StudentId = student.Id,
                                    FinalGrade = -1,
                                });
                            }
                        }

                        foreach (var grade in Grades)
                        {
                            await _gradeRepository.CreateAsync(grade);
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }
            }
            return View(model);
        }

        // GET: SubjectsController/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("SubjectNotFound");
            }

            var subject = await _subjectRepository.GetByIdAsync(id.Value);

            if (subject == null)
            {
                return new NotFoundViewResult("SubjectNotFound");
            }

            subject.Course = await _courseRepository.GetByIdAsync(subject.CourseId);
            subject.Teacher = await _teacherRepository.GetByIdAsync(subject.TeacherId);

            var model = _converterHelper.ToSubjectViewModel(subject, _courseRepository.GetAll().Where(c => c.Id > 1).Where(a => a.isActive == true),
                _teacherRepository.GetAll().Where(c => c.Id > 1).Where(a => a.isActive == true));

            return View(model);
        }

        // POST: SubjectsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SubjectViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var subject = _converterHelper.ToSubject(model, await _courseRepository.GetByIdAsync(model.CourseId),
                        await _teacherRepository.GetByIdAsync(model.TeacherId), true);

                    subject.Id = model.Id;

                    await _subjectRepository.UpdateAsync(subject);
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _subjectRepository.ExistsAsync(model.Id))
                    {
                        return new NotFoundViewResult("SubjectNotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return View(model);
        }

        /// <summary>
        /// Returns the View for the Upload Excel File Option
        /// </summary>
        /// <returns></returns>
        public IActionResult Upload()
        {
            return View();
        }

        /// <summary>

School.Web/Views/Subjects/Create.cshtml
@model School.Web.Models.SubjectViewModel

@{
    ViewData["Title"] = "Create";
}

<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb-area bg-img" style="background-image: url(../../img/bg-img/breadcumb.jpg);">
    <div class="bradcumbContent">
        <h2>Create Subject</h2>
    </div>
</div>
<!-- ##### Breadcumb Area End ##### -->
<!-- ##### About Us Area Start ##### -->
<section class="about-us-area mt-50 section-padding-100">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-heading text-center mx-auto wow fadeInUp" data-wow-delay="300ms">
                    <h3>Create Subject</h3>
                </div>
            </div>
        </div>
        <section class="contact-area">
            <div class="contact-content">
                <form asp-action="Edit" method="post" enctype="multipart/form-data" onsubmit="validation()">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-12 wow fadeInUp" data-wow-delay="500ms">
                            <!--BANNER START-->
                            <div class="panel single-accordion">
                                <h6>
                                    <a class="collapsed" style="text-align:center;">
                                        General Information
                                    </a>
                                </h6>
                            </div>
                            <!--BANNER END-->
                            <br />
                            <div class="contact-form-area wow fadeInUp" data-wow-delay="500ms">
                                <label asp-for="Code" class="form-label"><b>Code:</b></label>
                                <input asp-for="Code" type="text" class="form-control" id="code" readonly="readonly">
                                <label asp-for="Name" class="form-label"><b>Name:</b></label>
                                <input asp-for="Name" type="text" class="form-control" id="name" readonly="readonly">
                                <label asp-for="Field" class="form-label"><b>Field:</b></label>
                                <input asp-for="Field" type="text" class="form-control" id="field" readonly="readonly">
                                <label asp-for="CourseId" class="form-label"><b>Course:</b></label>
                                <label id="courseValidator" class="text-danger"></label>
                                <ejs-dropdownlist id="courses" ejs-for="CourseId" dataSource="Model.Courses" cssClass="e-filled" placeholder="Select a Course" index="2" popupHeight="230px" change="valueChange">
                                    <e-dropdownlist-fields text="Name" value="Id"></e-dropdownlist-fields>
                                </ejs-dropdownlist>
                                <label asp-for="TeacherId" class="form-label"><b>Teacher:</b></label>
                                <label id="teacherValidator" class="text-danger"></label>
                                <ejs-dropdownlist id="teachers" ejs-for="TeacherId" dataSource="Model.Teachers" cssClass="e-filled" placeholder="Select a Teacher" index="2" popupHeight="230px" change="valueChange">
                                    <e-dropdownlist-fields text="FullName" value="Id"></e-dropdownlist-fields>
                                </ejs-dropdownlist>
                            </div>
                        </div>
                        <div class="col-12 wow fadeInUp" data-wow-delay="500ms">
                            <h6><br /></h6>
                        </div>
                        <div class="col-12 wow fadeInUp" data-wow-delay="500ms">
                            <!--BANNER START-->
                            <div class="panel single-accordion">
                                <h6>
                                    <a class="collapsed" style="text-align:center;">
                                        Detailed Information
                                    </a>
                                </h6>
                            </div>
                            <!--BANNER END-->
                            <br />
                            <div class="contact-form-area wow fadeInUp" data-wow-delay="500ms">
                                <br />
                                <label asp-for="Duration" class="form-label"><b>Duration:</b></label>
                                <input asp-for="Duration" type="text" class="form-control" id="duration" readonly="readonly">
                                <label asp-for="Credits" class="form-label"><b>Credits:</b></label>
                                <label id="creditsValidator" class="text-danger"></label>
                                <input asp-for="Credits" type="text" class="form-control" id="credits" placeholder="Credits">
                                <label asp-for="QNQLevel" class="form-label"><b>QNQLevel:</b></label>
                                <input asp-for="QNQLevel" type="text" class="form-control" id="qnqlevel" readonly="readonly">
                                <label asp-for="Component" class="form-label"><b>Component:</b></label>
                                <input asp-for="Component" type="text" class="form-control" id="component" readonly="readonly">
                            </div>
                        </div>
                        <!-- ##### About Us Area End ##### -->
                        <input asp-action="Create" class="btn academy-btn mt-30" type="submit" value="Create" style="margin-left:30%" />
                        <a asp-action="Index" class="btn academy-btn mt-30" style="margin-left:5%">Back</a>
                    </div>
                </form>
            </div>
        </section>
    </div>
</section>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script>
    function validation() {
        var course = document.getElementById('courses').ej2_instances[0];
        var courseValidator = document.getElementById('courseValidator');

        var teacher = document.getElementById('teachers').ej2_instances[0];
        var teacherValidator = document.getElementById('teacherValidator');

        var credits = document.getElementById('credits').ej2_instances[0];
        var creditsValidator = document.getElementById('creditsValidator');
        debugger

        if (course.properties.value == 0) {
            courseValidator.innerText = "Field Course is mandatory";
            event.preventDefault();
        }
        if (teacher.properties.value == 0) {
            teacherValidator.innerText = "Field Teacher is mandatory";
            event.preventDefault();
        }
        if (credits.value == "No Selection") {
            creditsValidator.innerText = "Field Credits is mandatory";
            event.preventDefault();
        }   
    }
</script>

School.Web/Views/Subjects/CreateIndex.cshtml
@model School.Web.Models.SubjectViewModel

@{
    ViewData["Title"] = "Create";
}

<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb-area bg-img" style="background-image: url(../../img/bg-img/breadcumb.jpg);">
    <div class="bradcumbContent">
        <h2>Create Subject</h2>
    </div>
</div>
<!-- ##### Breadcumb Area End ##### -->
<!-- ##### About Us Area Start ##### -->
<section class="about-us-area mt-50 section-padding-100">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-heading text-center mx-auto wow fadeInUp" data-wow-delay="300ms">
                    <h3>Create Subject</h3>
                </div>
            </div>
        </div>
        <section class="contact-area">
            <div class="contact-content">
                <div class="contact-form-area wow fadeInUp" data-wow-delay="500ms">
                    <ejs-grid id="Grid" dataSource="@Model.IEFPSubjects" allowSorting="true" allowFiltering="true" allowPaging="true">
                        <e-grid-filterSettings type="Menu"></e-grid-filterSettings>
                        <e-grid-columns>
                            <e-grid-column field="Id" headerText="Id" visible="false" textAlign="Right" width="auto" type="number" isPrimaryKey="true"></e-grid-column>
                            <e-grid-column field="Code" headerText="Code" width="auto" type="string"></e-grid-column>
                            <e-grid-column field="Name" headerText="Name" width="auto" type="string"></e-grid-column>
                            <e-grid-column field="Field" headerText="Field" width="auto" type="string"></e-grid-column>
                            <e-grid-column template="#template" textAlign="Right" width="auto"></e-grid-column>
                        </e-grid-columns>
                    </ejs-grid>
                </div>
                <!-- ##### About Us Area End ##### -->
                <a asp-action="Upload" class="btn academy-btn mt-30" style="margin-left:33%">Upload Subjects</a>
                <a asp-action="Index" class="btn academy-btn mt-30" style="margin-left:3%">Back</a>
            </div>
        </section>
    </div>
</section>

<script id="template" type="text/x-template">
    <div>
        <a href='/Subjects/Create/${Id}'>Create</a>
    </div>
</script>

School.Web/Views/Subjects/Details.cshtml
@model School.Web.Data.Entities.Subject

@{
    ViewData["Title"] = "Details";
}

<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb-area bg-img" style="background-image: url(../../img/bg-img/breadcumb.jpg);">
    <div class="bradcumbContent">
        <h2>Subject Details</h2>
    </div>
</div>
<!-- ##### Breadcumb Area End ##### -->
<!-- ##### About Us Area Start ##### -->
<section class="about-us-area mt-50 section-padding-100">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-heading text-center mx-auto wow fadeInUp" data-wow-delay="300ms">
                    <h3>Subject Details</h3>
                </div>
            </div>
        </div>
        <section class="contact-area">
            <div class="contact-content">
                <div class="row">
                    <div class="col-12 wow fadeInUp" data-wow-delay="500ms">
                        <!--BANNER START-->
                        <div class="panel single-accordion">
                            <h6>
                                <a class="collapsed" style="text-align:center;">
                                    General Information
                                </a>
                            </h6>
                        </div>
                        <!--BANNER END-->
                        <br />
                        <div class="contact-form-area wow fadeInUp" data-wow-delay="500ms">
                            <label class="form-label"><b>Code:</b></label>
                            <div style="height:48px;">
                                <label class="form-label">@Html.DisplayFor(model => model.Code)</label> <br />
                            </div>
                            <label class="form-label"><b>Name:</b></label>
                            <div style="height:48px;">
                                <label class="form-label">@Html.DisplayFor(model => model.Name)</label> <br />
                            </div>
                            <label class="form-label"><b>Area:</b></label>
                            <div style="height:48px;">
                                <label class="form-label">@Html.DisplayFor(model => model.Field)</label> <br />
                            </div>
                            <label class="form-label"><b>Courses:</b></label>
                            <div style="height:48px;">
                                <label class="form-label">@Html.DisplayFor(model => model.Course.Name)</label> <br />
                            </div>
                            <label class="form-label"><b>Teacher:</b></label>
                            <div style="height:48px;">
                                <label class="form-label">@Html.DisplayFor(model => model.Teacher.FullName)</label> <br />
                            </div>
                        </div>
                    </div>
                    <div class="col-12 wow fadeInUp" data-wow-delay="500ms">
                        <h6><br /></h6>
                    </div>
                    <div class="col-12 wow fadeInUp" data-wow-delay="500ms">
                        <!--BANNER START-->
                        <div class="panel single-accordion">
                            <h6>
                                <a class="collapsed" style="text-align:center;">
                                    Detailed Information
                                </a>
                            </h6>
                        </div>
                        <!--BANNER END-->
                        <br />
                        <div class="contact-form-area wow fadeInUp" data-wow-delay="500ms">
                            <br />
                            <label class="form-label"><b>Duration:</b></label>
                            <div style="height:48px;">
                                <label class="form-label">@Html.DisplayFor(model => model.Duration)</label><br />
                            </div>
                            <label class="form-label"><b>Credits:</b></label>
                            <div style="height:48px;">
                                @if (Model.Credits == null)
                                {
                                    <label class="form-label">Not Selected</label><br />
                                }
                                @if (Model.Credits != null)
                                {
                                    <label class="form-label">@Html.DisplayFor(model => model.Credits)</label><br />
                                }
                            </div>
                            <label class="form-label"><b>QNQ Level:</b></label>
                            <div style="height:48px;">
                                <label class="form-label">@Html.DisplayFor(model => model.QNQLevel)</label><br />
                            </div>
                            <label class="form-label"><b>Component:</b></label>
                            <div style="height:48px;">
                                <label class="form-label">@Html.DisplayFor(model => model.Component)</label><br />
                            </div>
                        </div>
                    </div>
                    <!-- ##### About Us Area End ##### -->
                    <a asp-action="Index" class="btn academy-btn mt-30" style="margin-left:40%">Back</a>
                </div>
            </div>
        </section>
    </div>
</section>

School.Web/Views/Subjects/Import.cshtml
@model School.Web.Data.Entities.Subject

@{
    ViewData["Title"] = "Import";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />

@section Scripts{
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#MyTable').DataTable();
        });
    </script>
    <script>
        $('#MyTable').scrollTableBody();
    </script>
}

School.Web/Views/Subjects/Upload.cshtml
@model School.Web.Models.SubjectViewModel
@{
    ViewData["Title"] = "Upload";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />

<!-- ##### Breadcumb Area Start ##### -->
<div class="breadcumb-area bg-img" style="background-image: url(../../img/bg-img/breadcumb.jpg);">
    <div class="bradcumbContent">
        <h2>Upload Subjects</h2>
    </div>
</div>
<!-- ##### Breadcumb Area End ##### -->
<!-- ##### About Us Area Start ##### -->
<section class="about-us-area mt-50 section-padding-100">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section-heading text-center mx-auto wow fadeInUp" data-wow-delay="300ms">
                    <h3>Upload Subjects</h3>
                </div>
            </div>
        </div>
        <section class="contact-area">
            <div class="contact-content">
                <form asp-controller="Subjects" asp-action="Upload">
                    <div class="contact-form-area wow fadeInUp" data-wow-delay="500ms">
                        <div class="container">
                            <div class="row" style="align-items: start; justify-items: flex-start">
                                <div class="col-md-8" style="height:95px; padding-top:35px">
                                    <input type="file" id="fileupload" name="files" class="form-control" />
                                </div>
                                <div class="col-md-2">
                                    <input asp-action="Import" onclick="ShowSendingProgress()" type="button" class="btn academy-btn mt-30" name="Upload" value="Upload" id="btnupload" style="margin-top:-10px;" />
                                </div>
                                <div class="col-md-2">
                                    <div class="loading" align="center" style="display:none" id="modalSending">
                                        <img src="~/images/icon-loading.gif" style="height:120px"/>
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix">&nbsp;</div>
                            <div class="row">
                                <div id="divPrint" style="margin-left:-19px;"></div>
                            </div>
                        </div>
                        <!-- ##### About Us Area End ##### -->
                        <input asp-action="CreateIndex" class="btn academy-btn mt-30" type="submit" value="Create" style="margin-left:30%" />
                        <a asp-action="Index" class="btn academy-btn mt-30" style="margin-left:5%">Back</a>
                    </div>
                </form>
            </div>
        </section>
    </div>
</section>

<script>
    function ShowSendingProgress() {
        var modal = $('< div />');
        modal.addClass("modal");
        modal.attr("id", "modalSending");
        $('body').append(modal);
        var loading = $("#modalSending.loading");
        loading.show();
    }
    function StopProgress() {

        $("div.modal").hide();

        var loading = $(".loading");
        loading.hide();
    }
</script>
<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script type="text/javascript">
    $(function () {
        $('#btnupload').on('click', function () {
            var fileExtension = ['xls', 'xlsx'];
            var filename = $('#fileupload').val();
            if (filename.length == 0) {
                alert("Please select a file.");
                return false;
            }
            else {
                var extension = filename.replace(/^.*\./, '');
                if ($.inArray(extension, fileExtension) == -1) {
                    alert("Please select only excel files.");
                    return false;
                }
            }
            var fdata = new FormData();
            var fileUpload = $("#fileupload").get(0);
            var files = fileUpload.files;
            fdata.append(files[0].name, files[0]);

            $.ajax({
                type: "POST",
                url: "/Subjects/Import",
                beforeSend: function (xhr) {
                    xhr.setRequestHeader("XSRF-TOKEN",
                        $('input:hidden[name="__RequestVerificationToken"]').val());
                },
                data: fdata,
                contentType: false,
                processData: false,
                success: function (response) {
                    if (response.length == 0)
                        alert('Some error occured while uploading');
                    else {
                        $('#divPrint').html(response);
                        StopProgress();
                    }
                },
                error: function (e) {
                    $('#divPrint').html(e.responseText);
                }
            });
        })
    });
</script>

@section Scripts{
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
}