School.Web/Controllers/ClassesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using School.Web.Data.Repositories;
using School.Web.Helpers;
using School.Web.Models;
using Syncfusion.EJ2.Linq;
using System.Linq;
using System.Threading.Tasks;

namespace School.Web.Controllers
{
    public class ClassesController : Controller
    {
        private readonly IClassRepository _classRepository;
        private readonly ICourseRepository _courseRepository;
        private readonly ITeacherRepository _teacherRepository;
        private readonly IStudentRepository _studentRepository;
        private readonly ISubjectRepository _subjectRepository;
        private readonly IScheduleRepository _scheduleRepository;
        private readonly IClassroomRepository _classroomRepository;
        private readonly IConverterHelper _converterHelper;

        public ClassesController(IClassRepository classRepository, ICourseRepository courseRepository, ITeacherRepository teacherRepository,
            IStudentRepository studentRepository, ISubjectRepository subjectRepository, IScheduleRepository scheduleRepository,
            IClassroomRepository classroomRepository, IConverterHelper converterHelper)
        {
            _classRepository = classRepository;
            _courseRepository = courseRepository;
            _teacherRepository = teacherRepository;
            _studentRepository = studentRepository;
            _subjectRepository = subjectRepository;
            _scheduleRepository = scheduleRepository;
            _classroomRepository = classroomRepository;
            _converterHelper = converterHelper;
        }

        // GET: ClassesController
        public IActionResult Index()
        {
            return View(_classRepository.GetAll().Where(a => a.isActive == true)
                .Include(c => c.Course).Where(a => a.isActive == true)
                .Include(c => c.Classroom).Where(a => a.isActive == true)
                .Include(c => c.Schedule).Where(a => a.isActive == true));
        }

        [Authorize(Roles = "Admin, Teacher")]
        // GET: ClassesController/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ClassNotFound");
            }

            var classes = await _classRepository.GetByIdAsync(id.Value);//Value pq pode vir nulo

            var model = _converterHelper.ToClassViewModel(classes, await _courseRepository.GetByIdAsync(classes.CourseId),
                _studentRepository.GetAll().Where(e => e.ClassId == id.Value).Where(a => a.isActive == true),
                _subjectRepository.GetAll().Where(e => e.CourseId == classes.CourseId).Where(a => a.isActive == true));

            model.Teachers = _classRepository.GetTeachers(model, _teacherRepository.GetAll().Where(a => a.isActive == true), model.Subjects).ToList();

            var students = _studentRepository.GetAll().Where(e => e.ClassId == id.Value).Where(a => a.isActive == true);
            model.Students = students;

            model.Schedule = await _scheduleRepository.GetByIdAsync(classes.ScheduleId);
            model.Classroom = await _classroomRepository.GetByIdAsync(classes.ClassroomId);

            if (classes == null)
            {
                return new NotFoundViewResult("ClassNotFound");
            }

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        // GET: ClassesController/Create
        public IActionResult Create()
        {
            var model = new ClassViewModel
            {
                Courses = _courseRepository.GetAll().Where(c => c.Id > 1).Where(a => a.isActive == true).ToList(),
                Students = _studentRepository.GetAll().Where(a => a.isActive == true).ToList(),
                Classrooms = _classroomRepository.GetAll().Where(a => a.isActive == true).ToList(),
                Schedules = _scheduleRepository.GetAll().Where(a => a.isActive == true).ToList()
            };

            return View(model);
        }

        // POST: ClassesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ClassViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var classes = _converterHelper.ToClass(model, await _courseRepository.GetByIdAsync(model.CourseId), true);

                    await _classRepository.CreateAsync(classes);
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }                
            }
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        // GET: ClassesController/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ClassNotFound");
            }

            var classes = await _classRepository.GetByIdAsync(id.Value);
            if (classes == null)
            {
                return new NotFoundViewResult("ClassNotFound");
            }

            var model = _converterHelper.ToClassViewModel(classes, await _courseRepository.GetByIdAsync(classes.CourseId), _studentRepository.GetAll().Where(e => e.ClassId == id.Value).Where(a => a.isActive == true), _subjectRepository.GetAll().Where(e => e.CourseId == classes.CourseId).Where(a => a.isActive == true));

            model.Schedules = _scheduleRepository.GetAll().Where(a => a.isActive == true);
            model.Classrooms = _classroomRepository.GetAll().Where(a => a.isActive == true);

            model.Schedule = await _scheduleRepository.GetByIdAsync(classes.ScheduleId);
            model.Classroom = await _classroomRepository.GetByIdAsync(classes.ClassroomId);

            return View(model);
        }

        // POST: ClassesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ClassViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var classes = _converterHelper.ToClass(model, await _courseRepository.GetByIdAsync(model.CourseId), true);

                    classes.Id = model.Id;

                    await _classRepository.UpdateAsync(classes);
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _classRepository.ExistsAsync(model.Id))
                    {
                        return new NotFoundViewResult("ClassNotFound");
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        // GET: ClassesController/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new NotFoundViewResult("ClassNotFound");
            }

            var classes = await _classRepository.GetByIdAsync(id.Value);//Value pq pode vir nulo

            var model = _converterHelper.ToClassViewModel(classes, await _courseRepository.GetByIdAsync(classes.CourseId),
                _studentRepository.GetAll().Where(e => e.ClassId == id.Value).Where(a => a.isActive == true),
                _subjectRepository.GetAll().Where(e => e.CourseId == classes.CourseId).Where(a => a.isActive == true));

            model.Teachers = _classRepository.GetTeachers(model, _teacherRepository.GetAll().Where(a => a.isActive == true), model.Subjects).ToList();

            model.Students = _studentRepository.GetAll().Where(e => e.ClassId == id.Value).Where(a => a.isActive == true);
            model.Schedule = await _scheduleRepository.GetByIdAsync(classes.ScheduleId);
            model.Classroom = await _classroomRepository.GetByIdAsync(classes.ClassroomId);

            if (classes == null)
            {
                return new NotFoundViewResult("ClassNotFound");
            }

            return View(model);
        }

        // POST: ClassesController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var classes = await _classRepository.GetByIdAsync(id);
                await _classRepository.DeleteAsync(classes);
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateConcurrencyException)
            {
                throw;
            }            
        }
    }
}

School.Web/Controllers/GradesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using School.Web.Data.Repositories;
using School.Web.Helpers;
using School.Web.Models;
using Syncfusion.EJ2.Linq;
using System.Linq;
using System.Threading.Tasks;

namespace School.Web.Controllers
{
    public class GradesController : Controller
    {
        private readonly IGradeRepository _gradeRepository;

        public GradesController(IGradeRepository gradeRepository)
        {
            _gradeRepository = gradeRepository;
        }

        // GET: GradesController
        public IActionResult Index()
        {
            return View(_gradeRepository.GetAll().Where(a => a.isActive == true)
                .Include(c => c.Course)
                .Include(c => c.Class)
                .Include(c => c.Subject).Where(a => a.isActive == true)
                .Include(c => c.Teacher)
                .Include(c => c.Student).Where(a => a.isActive == true)
                .Where(g => g.FinalGrade >= 0));
        }

        [Authorize(Roles = "Admin")]
        // GET: GradesController/Create
        public IActionResult Create()
        {
            return View(_gradeRepository.GetAll().Where(a => a.isActive == true)
                .Include(c => c.Course)
                .Include(c => c.Class)
                .Include(c => c.Subject).Where(a => a.isActive == true)
                .Include(c => c.Teacher)
                .Include(c => c.Student).Where(a => a.isActive == true));
        }

        // POST: GradesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task Create([FromBody] GradeViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var grade = await _gradeRepository.GetByIdAsync(model.Id);

                    grade.FinalGrade = model.FinalGrade;
                    grade.Approval = model.FinalGrade >= 10 ? model.Approval = "Approved" : model.Approval = "Disapproved";

                    if (grade.FinalGrade >= 0 && grade.FinalGrade <= 20)
                    {
                        await _gradeRepository.UpdateAsync(grade);
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    throw;
                }                
            }
        }       
    }
}

School.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!-- Title -->
    <title>Academy - Education Course Template</title>

    <environment include="Development">
        <!-- Favicon -->
        <link rel="icon" href="~/img/core-img/favicon.ico">

        <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />

        <!-- Core Stylesheet -->
        <link rel="stylesheet" href="~/style.css" type="text/css">

        <!-- Syncfusion Essential JS 2 Styles -->
        <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />

        <!-- Sync Stylesheet -->
        <link rel="stylesheet" href="~/sync.css" type="text/css">

        <!-- DataTables Stylesheet -->
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
    </environment>
    <environment exclude="Development">
        <!-- Favicon -->
        <link rel="icon" href="~/img/core-img/favicon.ico">

        <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />

        <!-- Core Stylesheet -->
        <link rel="stylesheet" href="~/style.css" type="text/css">

        <!-- Syncfusion Essential JS 2 Styles -->
        <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/material.css" />

        <!-- Sync Stylesheet -->
        <link rel="stylesheet" href="~/sync.css" type="text/css">

        <!-- DataTables Stylesheet -->
        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
    </environment>
</head>
<body>
    <partial name="_CookieConsentPartial" />

    @*##### Preloader #####*@
    <div id="preloader">
        <i class="circle-preloader"></i>
    </div>

    @*##### Header Area Start #####*@
    <header class="header-area">

        @*Top Header Area*@
        <div class="top-header">
            <div class="container h-100">
                <div class="row h-100">
                    <div class="col-12 h-100">
                        <div class="header-content h-100 d-flex align-items-center justify-content-between">
                            <div class="academy-logo">
                                <a href="index.html"><img src="../img/core-img/logo.png" alt=""></a>
                            </div>
                            <div class="login-content">
                                @if (this.User.Identity.IsAuthenticated)
                                {
                                    <a asp-area="" asp-controller="Accounts" asp-action="ChangeUser">@this.User.Identity.Name |  </a>
                                    <a asp-area="" asp-controller="Accounts" asp-action="Logout">Logout</a>
                                }
                                else
                                {
                                    <a asp-area="" asp-controller="Accounts" asp-action="Login">Login / Register</a>
                                }
                                @*<a href="#">Register / Login</a>*@
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @*Navbar Area*@
        <div class="academy-main-menu">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    @*Menu*@
                    <nav class="classy-navbar justify-content-between" id="academyNav">

                        @*Navbar Toggler*@
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"><span></span><span></span><span></span></span>
                        </div>

                        @*Menu*@
                        <div class="classy-menu">

                            @*close btn*@
                            <div class="classycloseIcon">
                                <div class="cross-wrap"><span class="top"></span><span class="bottom"></span></div>
                            </div>

                            @*Nav Start*@
                            <div class="classynav" style="height:20px;">
                                <ul>
                                    <li><a asp-controller="" asp-action=""></a></li>
                                    <li><a asp-controller="" asp-action=""></a></li>
                                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                                    <li><a asp-controller="" asp-action=""></a></li>
                                    <li><a asp-controller="" asp-action=""></a></li>
                                    <li><a asp-controller="" asp-action=""></a></li>
                                    <li><a asp-controller="Home" asp-action="About">About</a></li>
                                    <li><a asp-controller="" asp-action=""></a></li>
                                    <li><a asp-controller="" asp-action=""></a></li>
                                    <li><a asp-controller="" asp-action=""></a></li>
                                    <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                                    <li><a asp-controller="" asp-action=""></a></li>
                                    <li><a asp-controller="" asp-action=""></a></li>
                                    <li><a asp-controller="" asp-action=""></a></li>
                                    <li><a asp-controller="Courses" asp-action="Index">Courses</a></li>
                                </ul>
                            </div>
                            @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin") || (this.User.Identity.IsAuthenticated && this.User.IsInRole("Teacher")) || (this.User.Identity.IsAuthenticated && this.User.IsInRole("Student")))
                            {
                                <div class="classynav">
                                    <ul>
                                        <li><a asp-controller="Students" asp-action="Index">Students</a></li>
                                        @if ((this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin")) || (this.User.Identity.IsAuthenticated && this.User.IsInRole("Teacher")))
                                        {
                                            <li><a asp-controller="" asp-action=""></a></li>
                                            <li><a asp-controller="Teachers" asp-action="Index">Teachers</a></li>
                                            <li><a asp-controller="" asp-action=""></a></li>
                                            <li><a asp-controller="Classes" asp-action="Index">Classes</a></li>
                                            <li><a asp-controller="" asp-action=""></a></li>
                                            <li><a asp-controller="Subjects" asp-action="Index">Subjects</a></li>
                                            <li><a asp-controller="" asp-action=""></a></li>
                                            <li><a asp-controller="Grades" asp-action="Index">Grades</a></li>
                                        }
                                        @if (this.User.Identity.IsAuthenticated && this.User.IsInRole("Admin"))
                                        {
                                            <li><a asp-controller="" asp-action=""></a></li>
                                            <li><a asp-controller="Accounts" asp-action="Settings">Settings</a></li>
                                        }
                                    </ul>
                                </div>
                            }
                            <div class="classynav"></div>
                            @*Nav End*@
                        </div>

                        @*Calling Info*@
                        <div class="calling-info">
                            <div class="call-center">
                                <a href="tel:21 123 45 67"><i class="icon-telephone-2"></i><span>(+351)21 1234567</span></a>
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ##### Header Area End ##### -->

    @RenderBody()

    <!-- ##### Footer Area Start ##### -->
    <environment include="Development">
        <!-- ##### All Javascript Script ##### -->
        <!-- jQuery-2.2.4 js -->
        <script src="~/js/jquery/jquery-2.2.4.min.js"></script>
        <!-- Popper js -->
        <script src="~/js/bootstrap/popper.min.js"></script>
        <!-- Bootstrap js -->
        <script src="~/js/bootstrap/bootstrap.min.js"></script>
        <!-- All Plugins js -->
        <script src="~/js/plugins/plugins.js"></script>
        <!-- Active js -->
        <script src="~/js/active.js"></script>
        <!-- Sync js -->
        <script src="~/js/sync.js"></script>

        <!-- Syncfusion Essential JS 2 Scripts -->
        <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
    </environment>
    <environment exclude="Development">
        <!-- ##### All Javascript Script ##### -->
        <!-- jQuery-2.2.4 js -->
        <script src="~/js/jquery/jquery-2.2.4.min.js"></script>
        <!-- Popper js -->
        <script src="~/js/bootstrap/popper.min.js"></script>
        <!-- Bootstrap js -->
        <script src="~/js/bootstrap/bootstrap.min.js"></script>
        <!-- All Plugins js -->
        <script src="~/js/plugins/plugins.js"></script>
        <!-- Active js -->
        <script src="~/js/active.js"></script>
        <!-- Sync js -->
        <script src="~/js/sync.js"></script>

        <!-- Syncfusion Essential JS 2 Scripts -->
        <script src="https://cdn.syncfusion.com/ej2/dist/ej2.min.js"></script>
    </environment>
    @RenderSection("Scripts", required: false)
    <ejs-scripts></ejs-scripts>
</body>
</html>

<!--DROPDWON MENU-->
@*<ul>
        <li>
            <a href="#">Back Office</a>
            <ul class="dropdown">
                <li><a asp-controller="Courses" asp-action="Index">Courses</a></li>
                <li><a asp-controller="Classes" asp-action="Index">Classes</a></li>
                <li><a asp-controller="Subjects" asp-action="Index">Subjects</a></li>
                <li><a asp-controller="Teachers" asp-action="Index">Teachers</a></li>
                <li><a asp-controller="Students" asp-action="Index">Students</a></li>
                <li><a asp-controller="Grades" asp-action="Index">Grades</a></li>
            </ul>
        </li>
        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
    </ul>*@

@*<environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>*@